"""Single-file HTML template for the ARAC atlas dashboard.

Uses Python's string.Template syntax (`$placeholder`) to avoid f-string conflicts
with the curly braces in JavaScript. Four placeholders:
- $atlas_data_json: a JSON-encoded array of atlas row dicts
- $generated_at: ISO 8601 UTC timestamp
- $summary: pre-rendered HTML for the summary stats section
- $row_count: total row count (used for the title)

Dollar signs that appear inside the JavaScript code are escaped as $$
per Python's string.Template rules so they are passed through literally.
"""

TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ARAC &mdash; African Representation Atlas of Cochrane</title>
<style>
:root {
  --bg: #f5f1e8;
  --fg: #2a2520;
  --accent: #8b3a1a;
  --muted: #7d7468;
  --card: #ffffff;
  --border: #d8cfbf;
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 24px;
  font-family: Georgia, "Iowan Old Style", serif;
  color: var(--fg);
  background: var(--bg);
  line-height: 1.55;
}
header {
  max-width: 1200px;
  margin: 0 auto 32px auto;
  border-bottom: 1px solid var(--border);
  padding-bottom: 16px;
}
h1 { margin: 0 0 8px 0; font-weight: normal; font-style: italic; font-size: 28px; }
.subtitle { color: var(--muted); font-size: 14px; }
main { max-width: 1200px; margin: 0 auto; }
.summary {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 20px 24px;
  margin-bottom: 24px;
}
.summary h2 {
  margin: 0 0 12px 0;
  font-size: 18px;
  font-weight: normal;
  color: var(--accent);
}
.summary-row { display: flex; flex-wrap: wrap; gap: 24px; }
.metric { min-width: 140px; }
.metric-value { font-size: 24px; font-weight: bold; color: var(--accent); }
.metric-label { font-size: 13px; color: var(--muted); margin-top: 2px; }
.controls {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 16px;
  margin-bottom: 24px;
  display: flex; gap: 12px; flex-wrap: wrap;
}
.controls label {
  font-size: 13px;
  display: flex; flex-direction: column; gap: 4px;
}
.controls input, .controls select {
  font-family: inherit;
  font-size: 14px;
  padding: 4px 8px;
  border: 1px solid var(--border);
  background: white;
  border-radius: 3px;
}
table {
  width: 100%;
  border-collapse: collapse;
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 4px;
  overflow: hidden;
}
th, td {
  text-align: left;
  padding: 8px 12px;
  border-bottom: 1px solid var(--border);
  font-size: 13px;
}
th {
  background: #efe9da;
  font-weight: bold;
  color: var(--accent);
  cursor: pointer;
  user-select: none;
}
th:hover { background: #e5dec8; }
tr:last-child td { border-bottom: none; }
.tag {
  display: inline-block;
  padding: 1px 8px;
  border-radius: 8px;
  font-size: 11px;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.tag-site { background: #d4d0bd; color: #4a4030; }
.tag-authorship { background: #c9d4c0; color: #2f4030; }
.tag-participant { background: #d4c0c8; color: #50253a; }
.tag-invisible { background: #ddd6c5; color: #806a40; }
.tag-flag { background: var(--accent); color: white; }
.placeholder {
  text-align: center;
  padding: 60px 20px;
  color: var(--muted);
  font-style: italic;
}
footer {
  max-width: 1200px;
  margin: 32px auto 0 auto;
  padding-top: 16px;
  border-top: 1px solid var(--border);
  font-size: 12px;
  color: var(--muted);
  text-align: center;
}
</style>
</head>
<body>
<header>
  <h1>ARAC &mdash; African Representation Atlas of Cochrane</h1>
  <div class="subtitle">Per-MA &times; per-Tier representation gap scores. Generated $generated_at &mdash; $row_count rows.</div>
</header>
<main>
  $summary
  <div class="controls" id="controls">
    <label>Tier
      <select id="filter-tier">
        <option value="">All</option>
        <option value="site">Site</option>
        <option value="authorship">Authorship</option>
        <option value="participant">Participant</option>
      </select>
    </label>
    <label>Visibility
      <select id="filter-vis">
        <option value="">All</option>
        <option value="visible">Visible only</option>
        <option value="invisible">Invisible only</option>
      </select>
    </label>
    <label>Reproduction gap
      <select id="filter-rep">
        <option value="">All</option>
        <option value="True">Has gap</option>
        <option value="False">No gap</option>
      </select>
    </label>
    <label>Search ma_id
      <input type="text" id="filter-ma" placeholder="CD000028">
    </label>
  </div>
  <div id="atlas-table"></div>
</main>
<footer>
  Generated by ARAC v0.7.0. Data is a snapshot &mdash; regenerate with <code>python scripts/build_atlas.py</code> &amp;&amp; <code>python scripts/build_dashboard.py</code>.
</footer>
<script>
var ATLAS = $atlas_data_json;

function renderTable(rows) {
  var root = document.getElementById('atlas-table');
  if (!rows.length) {
    root.innerHTML = '<div class="placeholder">The atlas is empty. Build it first via <code>python scripts/build_atlas.py</code>, then regenerate the dashboard.</div>';
    return;
  }
  var cols = ['ma_id', 'tier', 'k_total', 'k_subset', 'invisible',
              'reproduction_gap', 'precision_gap_ratio', 'sign_flip', 'heterogeneity_gap',
              'recommendation_change'];
  var colLabels = ['MA', 'Tier', 'k', 'k African', 'Invisible',
                   'Repro gap', 'CI ratio', 'Sign flip', 'Het gap', 'Rec change'];
  var html = '<table><thead><tr>';
  for (var i = 0; i < cols.length; i++) {
    html += '<th data-col="' + cols[i] + '">' + colLabels[i] + '</th>';
  }
  html += '</tr></thead><tbody>';
  for (var j = 0; j < rows.length; j++) {
    var r = rows[j];
    html += '<tr>';
    html += '<td><code>' + r.ma_id + '</code></td>';
    html += '<td><span class="tag tag-' + r.tier + '">' + r.tier + '</span></td>';
    html += '<td>' + r.k_total + '</td>';
    html += '<td>' + r.k_subset + '</td>';
    if (r.invisible === 'True') {
      html += '<td><span class="tag tag-invisible">invisible</span></td>';
      html += '<td>&mdash;</td><td>&mdash;</td><td>&mdash;</td><td>&mdash;</td><td>&mdash;</td>';
    } else {
      html += '<td>visible</td>';
      var repTag = r.reproduction_gap === 'True'
        ? '<span class="tag tag-flag">gap</span>' : 'no gap';
      html += '<td>' + repTag + '</td>';
      var ratio = r.precision_gap_ratio
        ? parseFloat(r.precision_gap_ratio).toFixed(2) : '&mdash;';
      html += '<td>' + ratio + '</td>';
      var flipTag = r.sign_flip === 'True'
        ? '<span class="tag tag-flag">FLIP</span>' : 'no flip';
      html += '<td>' + flipTag + '</td>';
      var hetTag = r.heterogeneity_gap === 'True'
        ? '<span class="tag tag-flag">het gap</span>' : 'no gap';
      html += '<td>' + hetTag + '</td>';
      var recTag = r.recommendation_change === 'True'
        ? '<span class="tag tag-flag">rec change</span>' : 'no change';
      html += '<td>' + recTag + '</td>';
    }
    html += '</tr>';
  }
  html += '</tbody></table>';
  root.innerHTML = html;
}

function applyFilters() {
  var tier = document.getElementById('filter-tier').value;
  var vis = document.getElementById('filter-vis').value;
  var rep = document.getElementById('filter-rep').value;
  var ma = document.getElementById('filter-ma').value.trim().toLowerCase();
  var rows = ATLAS;
  if (tier) rows = rows.filter(function(r) { return r.tier === tier; });
  if (vis === 'visible') rows = rows.filter(function(r) { return r.invisible === 'False'; });
  else if (vis === 'invisible') rows = rows.filter(function(r) { return r.invisible === 'True'; });
  if (rep) rows = rows.filter(function(r) { return r.reproduction_gap === rep; });
  if (ma) rows = rows.filter(function(r) { return r.ma_id.toLowerCase().indexOf(ma) !== -1; });
  renderTable(rows);
}

var controls = document.querySelectorAll('#controls select, #controls input');
for (var k = 0; k < controls.length; k++) {
  controls[k].addEventListener('input', applyFilters);
  controls[k].addEventListener('change', applyFilters);
}

renderTable(ATLAS);
</script>
</body>
</html>
"""
